### ISSUE TITLE
Vim Version 8.1 Error in provided vimrc file in Windows 10 Pro       

### ISSUE THREAD

**Issue by memenpu** [Hassan-Shabbir/vim-introduction#2] opened 2019-03-04 16:07 UTC
#### Breif Description
 I created a .vimrc file and edited with gVim to configure Vim, I pasted the configuration [codes written in text-editing.org](https://github.com/Hassan-Shabbir/vim-introduction/blob/master/text-editing.org#extending-vim-for-yourself)(click to see the codes) to the .vimrc file and saved it.  I reopened gVim to see if the theme was saved. But it pops up a window with error messages. 
##### Here is the screenshot of the window
![window with error message](https://user-images.githubusercontent.com/44709023/53745341-ddcb7780-3e6c-11e9-8fa2-82aeb302bfdb.png)
##### The error messages list; 
* line 35
* E518: Unknown option: set; 
* filetypedetect BufRead
##### the codes at line 35 
![the codes at line 35](https://user-images.githubusercontent.com/44709023/53745395-f0de4780-3e6c-11e9-802e-fb68ceb8b43b.png)
##### the codes about BufRead 
![BufRead](https://user-images.githubusercontent.com/44709023/53775151-5eb35f00-3ebf-11e9-9594-b849978833ec.png)

**Comment by Hassan-Shabbir** [comment] 2019-03-04 19:03
I'll let you fix this issue for practice. 

Alright, so if I can critique this issue: 

1. The title should be more along the lines of "error in provided vimrc file"
2. You should mention both errors (the one on the last line as well, since that is a part of the error message in this image)
3. You should be more descriptive in the message by including things such as:
    - The operating system you are using
    - The version for the operating system (if it has one)
    - The kernel version (if it has one)
    - Your GVim version
4. The simplest thing that causes the error 

So here are the reasons for the above responses. 

The title should be descriptive to help others be able to easily search for it under the issues search on GitHub. This will help others that have the same problem to solve it themselves. It should also help anyone reading it to know what the issue is about. "An error report" doesn't really quickly explain the problem.

You should include both errors since they are both caused by the same vimrc file. Usually however, you should make a new GitHub issue for each separate issue.

Your GitHub issue should always include the versions of the software involved in the problem, since an issue may have been fixed in a newer version that you are not currently using.

You should always simplify (isolate) the error. For example, before creating this issue you should backup the vimrc file, then delete all lines other than line 35. Then see if the issue still exists. If it does, then that means that the issue is caused by that one line, which will help the person helping you to easily see what the error is.

Finally, always remember that the other person is helping you for free while providing or maintaining the software that you use, so you should be courteous of their time and energy (ie. try to solve as much of the problem yourself).

Here is a good link (in general) for how to ask questions (and by extension how to create good issues on GitHub): http://www.catb.org/esr/faqs/smart-questions.html.

Good luck fixing this issue!

**Closed as completed** 2019-03-06 18:01 UTC
